# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: v1
kind: Ingress
metadata:
  name: microservice-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microservice-services
                port:
                  number: 80
